FROM node:16 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Використовуємо Nginx для продакшн обслуговування
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

# Змінимо конфігурацію Nginx для порту 3000
EXPOSE 3000

# Використовуємо Nginx для обслуговування статичних файлів на порті 3000
CMD ["nginx", "-g", "daemon off;"]
